language: ruby
cache: bundler
git:
  depth: 1000
script:
 - RAILS_ENV=test bundle exec rails db:migrate
 - bundle exec rspec spec/
before_install:
 - python -V
 - pip -V
 - sudo pip install -r travis/requirements.txt
 - python ./travis/try_issues.py
after_success:
 - git config --global user.email "hpi.swt2@gmail.com"
 - git config --global user.name "swt2public"
 - git checkout -b travis-tmp
 - git pull -X ours --no-edit "https://swt2public:wnjxeUn6pQpcnR4V@github.com/hpi-swt2-exercise/rails-exercise-16-tasks.git" master
 - bundle install && RAILS_ENV=test bundle exec rails db:migrate
 - bundle exec rspec spec/_tdd_tasks/ --fail-fast
 - bundle exec rspec spec/_tdd_tasks/ --fail-fast --format j --out report.txt
 - cat report.txt | python travis/submit_issue.py