language: ruby
cache: bundler
git:
  depth: 1000
script:
 - RAILS_ENV=test bundle exec rails db:migrate
 - bundle exec rspec spec/
before_install:
 - python -V
 - pip -V
 - sudo pip install -r travis/requirements.txt
 - python ./travis/try_issues.py
after_success:
 - wget -qO- https://hpi-swt2-exercise.github.io/rails-intro-exercise-tasks/tdd_tasks.tar.xz | tar xf
 - bundle exec rspec spec/_tdd_tasks/ --fail-fast
 - bundle exec rspec spec/_tdd_tasks/ --fail-fast --format j --out report.txt
 - cat report.txt | python travis/submit_issue.py